name: Tests
on:
   push:
      branches: [main, master]
   pull_request:
      branches: [main, master]
jobs:
   unit-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
              node-version: lts/*
         - name: Install dependencies
           run: npm ci
         - name: Run Vitest
           run: npm run test:run

   playwright-tests:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
              node-version: lts/*
         - name: Install dependencies
           run: npm ci
         - name: Build
           run: npm run build
           env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL}}
              SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
              NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
              NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
              NEXT_PUBLIC_ITEMS_PAGE_SIZE: ${{secrets.NEXT_PUBLIC_ITEMS_PAGE_SIZE}}
              NEXT_PUBLIC_WISHLIST_PAGE_SIZE: ${{secrets.NEXT_PUBLIC_WISHLIST_PAGE_SIZE}}
         - name: Install Playwright Browsers
           run: npx playwright install --with-deps
         - name: Run Playwright tests
           run: npx playwright test
           env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL}}
              SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
              NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
              NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
              NEXT_PUBLIC_ITEMS_PAGE_SIZE: ${{secrets.NEXT_PUBLIC_ITEMS_PAGE_SIZE}}
              NEXT_PUBLIC_WISHLIST_PAGE_SIZE: ${{secrets.NEXT_PUBLIC_WISHLIST_PAGE_SIZE}}
         - uses: actions/upload-artifact@v4
           if: ${{ !cancelled() }}
           with:
              name: playwright-report
              path: playwright-report/
              retention-days: 30
